included:
  - Sources
excluded:
  - .build
  - Package.swift

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - vertical_parameter_alignment_on_call
  - number_separator
  - unneeded_parentheses_in_closure_argument
  - trailing_closure
  - fatal_error_message

disabled_rules:
  - trailing_whitespace
  - line_length

force_cast: warning
force_try: warning
function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode" 