remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: WaterTracker
description: A modern macOS hydration tracking application
show_downloads: true
google_analytics:
github:
  is_project_page: true
  repository_url: https://github.com/yourusername/WaterTracker
  repository_name: WaterTracker
  owner_url: https://github.com/yourusername
  owner_name: Your Name

# Navigation
nav:
  - title: Home
    url: /
  - title: UI Guide
    url: /ui-guide
  - title: Project Structure
    url: /project-structure
  - title: Build Instructions
    url: /build-instructions
  - title: Contributing
    url: /contributing

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore 